openapi: "3.0.2"
info:
  title: UrlShortener API
  version: "1.0"
servers:
  - url: http://localhost:8000/
components:
  schemas:
    error:
      type: object
      properties:
        detail:
          description: error message
          type: string
          required: true
    InfoResponse:
      type: object
      properties:
        detail:
          description: object message
          type: string
          required: true
paths:
  /api/v1/make_shorter:
    post:
      summary: make vip link
      description: creates short url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                long_url:
                  description: url to make shorter
                  type: string
                  default: https://yandex.ru
                vip_key:
                  description: short key to be mapped to long url
                  type: string
                  required: false
                ttl:
                  description: |
                    number of time-units this short url is going to be active. 
                    Maximum value must not be more than 48 hours
                  type: integer
                  required: false
                  default: 10
                ttl_unit:
                  description: time unit for time_to_live parameter
                  type: string
                  enum:
                    - SECONDS
                    - MINUTES
                    - HOURS
                    - DAYS
                  required: false
                  default: HOURS
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                  secret_key:
                    type: string
        '400':
          description: invalid input parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/v1/admin/{secretKey}:
    delete:
      summary: Delete row by secret key
      parameters:
        - name: secretKey
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Secret key not found
    get:
      summary: Get information by secret key
      parameters:
        - name: secretKey
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
        '400':
          description: Secret key not found
  /api/v1/{shortSuffix}:
    get:
      summary: Redirect to the original link
      parameters:
        - name: shortSuffix
          in: path
          required: true
          schema:
            type: string
      responses:
        '307':
          description: Redirect to the original link
        '404':
          description: Short suffix not found
  /api/v1/healthcheck/ping:
    get:
      summary: Health check
      responses:
        '200':
          description: OK